binary_sensor:
  - platform: gpio
    pin:
      number: D3
      mode: INPUT_PULLUP
    name: "Rotary Encoder Button"
    on_click:
			min_length: 10ms
			max_length: 1s
      then:
				- script.execute: countdown
			min_length: 1s
			max_length: 5s
			then:
				- number.set:
						id: current_encoder_percent
						value: 0
				- sensor.rotary_encoder.set_value:
						id: blinds_encoder
						value: !lambda return id(min_encoder_value).state;