interval:
  - interval: 500ms
    then:
      - lambda: |-
          if (id(is_running) && (millis() - id(last_encoder_update)) > id(error_delay).state) {
              ESP_LOGD("custom", "Motor stalled or encoder not updating. Stopping the motor.");
              id(shade).make_call().set_command_stop().perform();
              id(motor_state).publish_state(id(motor_state_error));
          } else if (id(override_encoder)) {
              id(motor_state).publish_state(id(motor_state_calibrating));
          } else {
              id(motor_state).publish_state(id(motor_state_ok));
          }

          if (id(is_running) && (millis() - id(last_encoder_update)) > id(screen_off_delay).state) {
              ESP_LOGD("custom", "Turning off OLED...");
              id(is_display_on).publish_state(false);
          }