output:
  - platform: gpio
    id: motor_direction_up
    pin: D5

  - platform: gpio
    id: motor_direction_down
    pin: D6

  - platform: esp8266_pwm
    id: motor_enable
    pin: D0
    frequency: 1000 Hz