# Define the motor control pins
output:
  - platform: gpio
    id: motor_direction_up
    pin: D4

  - platform: gpio
    id: motor_direction_down
    pin: D5

  - platform: esp8266_pwm
    id: motor_enable
    pin: D8
    frequency: 1000 Hz  # Adjust the frequency as needed