substitutions:
  encoder_pin_a: "D1"
  encoder_pin_b: "D2"
  
esphome:
  name: template-shade
  platform: ESP8266
  board: nodemcuv2

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Template Shade Fallback"
    password: !secret template_shade_fallback_password

web_server:
  port: 80

captive_portal:

# Enable logging
logger:
  level: DEBUG

# Enable Home Assistant API
api:
  encryption:
    key: !secret template_shade_api_key

ota:
  password: !secret template_shade_ota_password

<<: !include ./shade_components/cover.yaml
<<: !include ./shade_components/globals.yaml
<<: !include ./shade_components/interval.yaml
<<: !include ./shade_components/number.yaml
<<: !include ./shade_components/output.yaml
<<: !include ./shade_components/script.yaml
<<: !include ./shade_components/sensor.yaml
<<: !include ./shade_components/switch.yaml